import { type NextPage } from "next";
import Head from "next/head";

const TOSPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>WoofAi - Terms of Service</title>
        <meta
          name="WoofAi AI powered dog icon generator"
          content="terms of service page for dog icon generator app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto my-8 flex max-w-[1024px] flex-col space-y-4 sm:my-12">
        <h2>Terms of Service</h2>
        <h3>Effective Date: 23 September 2023</h3>
        <h4>1. Acceptance of Terms</h4>
        <p>
          Welcome to WoofAI, an AI icon generator site operated by WoofAI Pty
          Ltd, located in Sydney, Australia. By accessing or using our services,
          you agree to comply with and be bound by these Terms of Service. If
          you do not agree with these terms, please do not use our services.
        </p>
        <h4> 2. Description of Services</h4>
        <p>
          WoofAI provides users with the ability to generate AI-powered icons
          and other related design assets through our online platform. These
          services may be subject to change or termination at our discretion.
        </p>
        <h4>3. User Registration</h4>
        <p>
          To use certain features of WoofAI, you may be required to register for
          an account. You agree to provide accurate and complete information
          during the registration process and to keep your account information
          up-to-date. You are responsible for maintaining the confidentiality of
          your account credentials and for any activities that occur under your
          account.
        </p>
        <h4>4. Use of Services</h4>
        <p>
          You agree to use WoofAI&apos;s services in compliance with all
          applicable laws and regulations. You shall not engage in any
          activities that:
        </p>
        <ol className="space-y-2 pl-6">
          <li>a. Violate any intellectual property rights;</li>
          <li>b. Are illegal, unethical, or harmful;</li>
          <li>c. Disrupt the integrity or performance of our services;</li>
          <li>d. Attempt to gain unauthorized access to our systems;</li>
          <li>e. Transmit viruses or malware.</li>
        </ol>
        <h4>5. Ownership and License</h4>
        <p>
          All content and intellectual property rights on WoofAI, including but
          not limited to logos, trademarks, icons, and designs, are owned by
          WoofAI Pty Ltd. You are granted a limited, non-exclusive,
          non-transferable license to use the icons and designs generated by
          WoofAI for personal or commercial purposes, subject to compliance with
          these Terms of Service.
        </p>
        <h4>6. Payments</h4>
        <p>
          Certain features or services may require payment. You agree to pay all
          fees and charges associated with your use of WoofAI in accordance with
          our pricing and payment terms. Payments are processed through secure
          third-party payment processors.
        </p>
        <h4>7. Privacy Policy</h4>
        <p>
          Your use of WoofAI is also governed by our Privacy Policy, which
          outlines how we collect, use, and disclose your personal information.
          By using WoofAI, you consent to the practices described in the Privacy
          Policy.
        </p>
        <h4>8. Termination</h4>
        <p>
          We reserve the right to terminate or suspend your access to WoofAI at
          our discretion, with or without cause, and without notice. Upon
          termination, your rights to use the services will cease immediately.
        </p>
        <h4>9. Disclaimer of Warranties</h4>
        <p>
          WoofAI is provided &quot;as is&quot; without warranties of any kind,
          whether express or implied. We do not guarantee the accuracy,
          reliability, or availability of our services. You use WoofAI at your
          own risk.
        </p>
        <h4>10. Limitation of Liability</h4>
        <p>
          To the extent permitted by law, WoofAI Pty Ltd shall not be liable for
          any indirect, incidental, special, consequential, or punitive damages
          arising from your use of WoofAI, even if we have been advised of the
          possibility of such damages.
        </p>
        <h4>11. Governing Law</h4>
        <p>
          These Terms of Service are governed by the laws of New South Wales,
          Australia. Any disputes arising from or related to these terms shall
          be subject to the exclusive jurisdiction of the courts in New South
          Wales.
        </p>
        <h4>12. Changes to Terms</h4>
        <p>
          We reserve the right to update or modify these Terms of Service at any
          time. You are responsible for regularly reviewing these terms. Your
          continued use of WoofAI after any changes constitutes acceptance of
          the updated terms.
        </p>
        <h4>13. Contact Us</h4>
        <p>
          If you have any questions or concerns about these Terms of Service,
          please contact us at: WoofAI Pty Ltd. Thank you for using WoofAI! We
          hope you enjoy our AI icon generator services.
        </p>
      </main>
    </>
  );
};

export default TOSPage;
